Controllers/PersonnelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using System.IO;
using System.Xml.Linq;
using System.Net.Mail;

namespace FirstProjetNRT.Models
{
    public class PersonnelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index2(string searchString)
        {
            XElement doc = XElement.Load("https://richnjembcptedatabase.blob.core.windows.net/nrtct/Personnel1.xml");
            IEnumerable<Personnel> process =

                    from artikel in doc.Descendants("PERSO")
                    where artikel.Element("Matricule").Value.Equals(searchString)
                    

            select new Personnel
                    {
                        NumId = (Int32)artikel.Element("NumId"),
                        Matricule = (string)artikel.Element("Matricule"),
                        Nom = (string)artikel.Element("Nom"),
                        Prenom = (string)artikel.Element("Prenom"),
                        Sexe = (string)artikel.Element("Sexe"),
                        Poste = (string)artikel.Element("Poste"),
                        Departement = (string)artikel.Element("Departement"),
                        Statut = (string)artikel.Element("Statut"),
                        Nationalite = (string)artikel.Element("Nationalite")

            };
                
            
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    var user = process.Where(o => o.Matricule.Equals(searchString) );
                    if (user.Any())
                    {
                       ViewBag.Mat= process.FirstOrDefault().Matricule;
                        ViewBag.Nom = process.FirstOrDefault().Nom;
                        ViewBag.Prenom = process.FirstOrDefault().Prenom;
                        //return RedirectToAction("Index", "Home");
                    }
                    
                    else
                    {
                    ModelState.AddModelError("", "The password provided is incorrect.");
                    }
                        
                }
                else
                {
                    ModelState.AddModelError("", "The user login or password provided is incorrect.");
                }

            }
           

            return View(process);



        }

        [HttpPost]
        public IActionResult Index3(string searchString)
        {
            XElement doc = XElement.Load("https://richnjembcptedatabase.blob.core.windows.net/nrtct/Personnel1.xml");
            IEnumerable<Personnel> process =

                    from artikel in doc.Descendants("PERSO")
                    where artikel.Element("Matricule").Value.Equals(searchString)
                    select new Personnel
                    {
                        NumId = (Int32)artikel.Element("NumId"),
                        Matricule = (string)artikel.Element("Matricule"),
                        Nom = (string)artikel.Element("Nom"),
                        Prenom = (string)artikel.Element("Prenom"),
                        Sexe = (string)artikel.Element("Sexe"),
                        Poste = (string)artikel.Element("Poste"),
                        Departement = (string)artikel.Element("Departement"),
                        Statut = (string)artikel.Element("Statut"),
                        Nationalite = (string)artikel.Element("Nationalite")

                    };
            if (!String.IsNullOrEmpty(searchString))
            {
                var user = process.Where(o => o.Matricule.Equals(searchString));
                if (user.Any())
                {
                    ViewBag.Mat = user.FirstOrDefault().Matricule;
                    ViewBag.Nom = user.FirstOrDefault().Nom;
                    ViewBag.Prenom = user.FirstOrDefault().Prenom;
                   // return RedirectToAction("Index", "Personnel");
                }


               
            }
           
           return View(process);
            
        }

        [HttpPost]
        public IActionResult Index(string searchString)
        {
            XElement doc = XElement.Load("https://richnjembcptedatabase.blob.core.windows.net/nrtct/Personnel1.xml");
            var q = from artikel in doc.Descendants("PERSO")
                    where artikel.Element("Matricule").Value.Contains(searchString)
                    select artikel.Elements().ToList();

            foreach (var r in q)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    if  (r[1].Value== searchString)
                    {
                ViewBag.Mat = r[1].Value;
                ViewBag.Nom = r[2].Value;
                ViewBag.Prenom = r[3].Value;
                       
                        goto exit;
                        //  return RedirectToAction("Index", "Personnel");
                    }
                }
                  
             
            }


        exit:
            
            return View();

           

        }

        
        public IActionResult Affichedata()
        {
            XElement doc = XElement.Load("https://richnjembcptedatabase.blob.core.windows.net/nrtct/Personnel1.xml");
            IEnumerable<Personnel> process =

                    from artikel in doc.Descendants("PERSO")
                   where artikel.Element("Matricule").Value.Equals("")

                    select new Personnel
                    {
                        NumId = (Int32)artikel.Element("NumId"),
                        Matricule = (string)artikel.Element("Matricule"),
                        Nom = (string)artikel.Element("Nom"),
                        Prenom = (string)artikel.Element("Prenom"),
                        Sexe = (string)artikel.Element("Sexe"),
                        Poste = (string)artikel.Element("Poste"),
                        Departement = (string)artikel.Element("Departement"),
                        Statut = (string)artikel.Element("Statut"),
                        Nationalite = (string)artikel.Element("Nationalite")

                    };
            
            ViewBag.List = process;
            ViewData["process"] = process;
            return View(process);
               
        }
        [HttpPost]
        public IActionResult Affichedata(string searchString)
        {
            XElement doc = XElement.Load("https://richnjembcptedatabase.blob.core.windows.net/nrtct/Personnel1.xml");
            IEnumerable<Personnel> process =

                    from artikel in doc.Descendants("PERSO")
                          where artikel.Element("Matricule").Value.Contains(searchString)



                    select new Personnel
                    {
                        NumId = (Int32)artikel.Element("NumId"),
                        Matricule = (string)artikel.Element("Matricule"),
                        Nom = (string)artikel.Element("Nom"),
                        Prenom = (string)artikel.Element("Prenom"),
                        Sexe = (string)artikel.Element("Sexe"),
                        Poste = (string)artikel.Element("Poste"),
                        Departement = (string)artikel.Element("Departement"),
                        Statut = (string)artikel.Element("Statut"),
                        Nationalite = (string)artikel.Element("Nationalite")

                    };

            ViewBag.List = process;
            ViewData["process"] = process;
            return View(process);

        }

    }
}

        
           
            


           
        
   

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewData["Title"] BPCSudcam
    </title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="container">
    <div class="font-header">GESTION DE BON DE</div>
    <div class="font-header">PRISE EN CHARGE</div>
    <div class="font-header1">PERSONNEL/PATIENT</div>
    <div class="font-header">RESEAU DE SOINS</div>
    <div class="font-header1">FCB/SUDCAM</div>

    <div class="rectangle">
        <a class="font-text" asp-area="" asp-controller="Personnel" asp-action="Affichedata">DEMANDE DE BON</a>
    </div>
    </br>
    <div class="rectangle">
        <a class="font-text" asp-area="" asp-controller="Login" asp-action="index">EMISSION DE BON</a>
    </div>
    </br>
    <div class="rectangle1">
        <a class="font-text1" asp-area="" asp-controller="Login" asp-action="Index">BONS SOCIAUX</a>
    </div>
    </br>
    <div class="rectangle">
        <a class="font-text" asp-area="" asp-controller="Login" asp-action="Index">DOSSIERS MEDICAUX</a>
    </div>
    </br>
    <div class="rectangle">
        <a class="font-text" asp-area="" asp-controller="Login" asp-action="Index">ETATS FINANCIERS</a>
    </div>


    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
<footer class="footer">

    Copyright  &copy; 2022 - BPCSudcam

</footer>
</html>

Views/Shared/_MyNewLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @{
        ViewBag.Title = "Connexion BCP SudCam";
      }
    <title>
    @ViewData["Title"] - Se Connecter </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>




        @RenderSection("Scripts", required: false)
</body>
</html>